/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Water;

import Employee.Customer;
import Employee.SensorValue;
import Employee.SourceSensor;
import Employee.WaterSupplyAdmin;
import Enterprise.Enterprise;
import UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Bhavesh Patel
 */
public class SupplyWaterJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SupplyWaterJPanel
     */
    private Customer customer;
    private JPanel container;
    private Enterprise enterprise;
    private UserAccount userAccount;
    public SupplyWaterJPanel(JPanel container, Enterprise enterprise,Customer customer,UserAccount userAccount) {
        initComponents();
        this.enterprise = enterprise;
        this.customer = customer;
        this.container = container;
        this.userAccount = userAccount;
        cust.setText(customer.getName());
        admin.setText(userAccount.getEmployee().getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cust = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        admin = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        flow = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        pressure = new javax.swing.JTextField();
        button = new javax.swing.JButton();
        volume = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Customer");

        cust.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Admin");

        admin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jButton2.setText("<<Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Supply Volume (Gallons)");

        jLabel4.setText("Flow Rate(Gallons/hr)");

        jLabel5.setText("Pressure");

        button.setText("Add Sensor value");
        button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActionPerformed(evt);
            }
        });

        jLabel6.setText("Sensor Name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(32, 32, 32)
                        .addComponent(cust, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(155, 155, 155)
                        .addComponent(jLabel3)
                        .addGap(45, 45, 45)
                        .addComponent(admin, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(219, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(39, 39, 39)
                        .addComponent(volume, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(flow, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                            .addComponent(name))
                        .addGap(56, 56, 56)
                        .addComponent(jLabel5)
                        .addGap(30, 30, 30)
                        .addComponent(pressure, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(admin, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cust, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))))
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(volume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                .addComponent(button)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(flow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(pressure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(187, 187, 187)
                .addComponent(jButton2)
                .addGap(36, 36, 36))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
        
        int index = container.getComponentCount() - 1;
      WaterSupplyAdminWorkAreaJPanel panel = (WaterSupplyAdminWorkAreaJPanel) container.getComponent(index);
      panel.populateTable();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonActionPerformed
        int a = (int) volume.getValue();
        if(a<=0){
            JOptionPane.showMessageDialog(null, "Supply volume cannot be negative");
            return;
        }
        float b =0;
        float c = 0;
        try{
           b= Float.parseFloat(flow.getText());
           c= Float.parseFloat(pressure.getText());
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Input Float Values only");
        }
        if(b<0 || c<0){
            JOptionPane.showMessageDialog(null, "Flow rate or pressure cannot be negative");
            return;
        }
        SourceSensor sourceSensor = new SourceSensor();
        sourceSensor.setCustomer(customer);
        sourceSensor.setSensorName(name.getText());
        sourceSensor.setSupplyVolume(a);
        sourceSensor.getSensorValue().setFlowrate(b);
        sourceSensor.getSensorValue().setPressure(c);
        
        customer.setSourceSensor(sourceSensor);
        customer.setVolumeAvailable(a);
        customer.getTargetSensor().setSensorName(name.getText());
        
        SensorValue sensorValue = new SensorValue();
        sensorValue.setFlowrate(b);
        sensorValue.setPressure(c);
        sensorValue.setDate(new Date());
        customer.getTargetSensor().getSensorValueList().add(sensorValue);
        
        WaterSupplyAdmin waterSupplyAdmin = (WaterSupplyAdmin) userAccount.getEmployee();
        waterSupplyAdmin.getSensorList().add(sourceSensor);
        JOptionPane.showMessageDialog(null, "Values set Successfully");
        button.setEnabled(false);
        name.setEnabled(false);
        flow.setEnabled(false);
        pressure.setEnabled(false);
        volume.setEnabled(false);
        
        
    }//GEN-LAST:event_buttonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel admin;
    private javax.swing.JButton button;
    private javax.swing.JLabel cust;
    private javax.swing.JTextField flow;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField name;
    private javax.swing.JTextField pressure;
    private javax.swing.JSpinner volume;
    // End of variables declaration//GEN-END:variables
}
